#!/bin/bash
bower install
npm install
gulp build
gulp config --env local
cordova plugin add com.ionic.keyboard # not 100% why this isn't installed properly otherwise

echo "Setup completed"
echo "Run 'ionic serve' to start the server"